Create docker-image.yml
itteco/iframely pull request #561
Opened 2024-10-28 18:59 UTC by Its4Nik

This will allow automatic image building using a GitHub Workflow.

The built image will be available under the GitHGub container registry (ghcr.io)

2024-10-28 19:41 UTC, electronick commented
@Its4Nik we really appreciate your effort on this one. It would be great if you could upgrade your PR a bit considering my comment above. Thanks!

2024-10-28 19:50 UTC, Its4Nik commented
> @Its4Nik we really appreciate your effort on this one. It would be great if you could upgrade your PR a bit considering my comment above. Thanks!

I am unsure which comment you are referring to, I can't seem to find it...

2024-10-29 15:08 UTC, electronick requested changes
pmorelli92/github-container-registry-build-push should be updated to docker/build-push-action

2024-10-29 16:05 UTC, Its4Nik commented on .github/workflows/docker-image.yml
> +            - uses: pmorelli92/github-container-registry-build-push@2.2.1
Im gonna adjust it accordingly

2024-12-18 21:45 UTC, electronick approved these changes
Thank you for your effort, @Its4Nik

2024-12-18 21:48 UTC, merged